import React from 'react'
import LessonLayout from '../../components/LessonLayout.jsx'
import CodeBlock from '../../components/CodeBlock.jsx'
import Quiz from '../../components/Quiz.jsx'
import GlossaryTooltip from '../../components/GlossaryTooltip.jsx'

// ── Code snippet constants (extracted from JSX props) ──
const CODE_LINUXFILESYSTEM_1 = `ssh user@192.168.100.20
ls -lah /          # List root with sizes
man hier           # Read the filesystem hierarchy manual`
const CODE_LINUXFILESYSTEM_2 = `total 76K
drwxr-xr-x  20 root root 4.0K Jan 15 09:00 .
drwxr-xr-x  20 root root 4.0K Jan 15 09:00 ..
lrwxrwxrwx   1 root root    7 Jan 15 09:00 bin -> usr/bin
drwxr-xr-x   4 root root 4.0K Jan 15 09:00 boot
drwxr-xr-x  18 root root 3.8K Jan 15 09:00 dev
drwxr-xr-x 135 root root  12K Jan 15 09:00 etc
...`
const CODE_LINUXFILESYSTEM_3 = `df -h                   # Filesystem-level space usage
du -sh /var/log/*      # Per-log-file sizes
du -sh /home/*         # Per-user home directory sizes
ncdu /                 # Interactive disk usage (install: apt install ncdu)`
const CODE_LINUXFILESYSTEM_4 = `Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1        30G  4.2G   24G  15% /
tmpfs           994M     0  994M   0% /dev/shm`
const CODE_LINUXFILESYSTEM_5 = `cat /proc/cpuinfo | grep "model name" | head -1
cat /proc/meminfo | grep MemTotal
cat /proc/uptime             # Seconds since boot
ls /proc/1/                  # systemd process (PID 1) info
cat /proc/net/tcp            # Active TCP connections (raw)`
const CODE_LINUXFILESYSTEM_6 = `mkdir -p ~/lab/configs ~/lab/logs
touch ~/lab/configs/app.conf

# Create a symbolic link
ln -s ~/lab/configs/app.conf ~/lab/app-link

# Verify
ls -lah ~/lab/
# Notice: app-link -> /home/user/lab/configs/app.conf

# Hard link
ln ~/lab/configs/app.conf ~/lab/app-hardlink
ls -lai ~/lab/configs/app.conf ~/lab/app-hardlink
# Same inode number = same file`
const CODE_LINUXFILESYSTEM_7 = `# Navigation
pwd                   # Print working directory
ls -lah               # List all files with permissions and sizes
cd /path              # Change directory
cd ~                  # Go to home directory
cd -                  # Go to previous directory

# File info
file /bin/ls          # Determine file type
stat /etc/passwd      # Detailed metadata
which python3         # Full path to a command
whereis bash          # Binary, source, and man page locations

# Disk usage
df -h                 # Filesystem-level free/used space
du -sh /var/log       # Directory size summary
du -sh /var/log/*     # All items in directory
ncdu /                # Interactive disk usage browser

# Finding files
find / -name "*.conf" -type f 2>/dev/null
find /etc -name "*.conf" -newer /etc/passwd
locate nginx.conf     # Fast search using updatedb index

# Links
ln source target      # Hard link
ln -s source target   # Symbolic link
readlink -f symlink   # Resolve symlink to real path`


const QUIZ_QUESTIONS = [
  {
    id: 'q1',
    question: 'Which directory contains system-wide configuration files in Linux?',
    options: ['/bin', '/etc', '/var', '/usr'],
    correct: 1,
    explanation: '/etc contains all system-wide configuration files (e.g., /etc/passwd, /etc/ssh/sshd_config, /etc/fstab). It does not contain binaries or user data.',
  },
  {
    id: 'q2',
    question: 'What does the /proc filesystem contain?',
    options: [
      'Process log files and crash dumps',
      'A virtual filesystem exposing kernel and process information in real-time',
      'The /usr/bin programs for process management',
      'Temporary process files that survive reboots',
    ],
    correct: 1,
    explanation: '/proc is a virtual filesystem — nothing on it is stored on disk. It is generated by the kernel at runtime and exposes process information (/proc/1234/) and system info (/proc/cpuinfo, /proc/meminfo).',
  },
  {
    id: 'q3',
    question: 'Which command shows disk usage of a directory and its contents?',
    options: ['df -h /home', 'ls -lah /home', 'du -sh /home/*', 'stat /home'],
    correct: 2,
    explanation: 'du (disk usage) measures how much disk space a directory and its contents consume. -s gives a summary per argument, -h makes it human-readable. df shows filesystem-level free/used space, not per-directory usage.',
  },
  {
    id: 'q4',
    question: 'What is the purpose of /var/log?',
    options: [
      'Variable-length binary programs',
      'System and application log files that grow over time',
      'Virtual memory swap files',
      'Volatile temporary files cleared on boot',
    ],
    correct: 1,
    explanation: '/var contains variable data that changes during normal system operation. /var/log specifically holds log files — /var/log/syslog, /var/log/auth.log, /var/log/nginx/access.log, etc.',
  },
  {
    id: 'q5',
    question: 'What does the command "ln -s /etc/nginx/nginx.conf ~/nginx.conf" create?',
    options: [
      'A hard link to nginx.conf in the home directory',
      'A copy of nginx.conf in the home directory',
      'A symbolic (soft) link pointing to /etc/nginx/nginx.conf',
      'A mount point for the nginx config directory',
    ],
    correct: 2,
    explanation: 'ln -s creates a symbolic link (symlink) — a file that points to another file\'s path. Unlike a hard link, a symlink can cross filesystem boundaries and works with directories. The -s flag is what makes it symbolic rather than a hard link.',
  },
]

function Callout({ type = 'info', icon, title, children }) {
  const s = { info: 'callout-info', warning: 'callout-warning', danger: 'callout-danger', success: 'callout-success' }
  return (
    <div className={`callout ${s[type]}`}>
      <span className="callout-icon">{icon}</span>
      <div className="callout-body">{title && <strong>{title}</strong>}{children}</div>
    </div>
  )
}

function LabStep({ number, description, command, output }) {
  return (
    <div className="space-y-2">
      <div className="flex items-start gap-3">
        <span className="w-6 h-6 rounded-full bg-accent-amber/20 border border-accent-amber/30
                         text-accent-amber text-[11px] font-bold font-mono flex items-center
                         justify-center flex-shrink-0 mt-0.5">{number}</span>
        <p className="text-sm text-slate-300 leading-relaxed">{description}</p>
      </div>
      {command && <div className="ml-9"><CodeBlock code={command} language="bash" showCopy /></div>}
      {output && (
        <div className="ml-9 rounded-xl bg-surface-950 border border-surface-700 px-4 py-3
                        font-mono text-xs text-accent-green leading-6">
          {output.split('\n').map((l, i) => <div key={i}>{l}</div>)}
        </div>
      )}
    </div>
  )
}

export default function LinuxFilesystem() {
  return (
    <LessonLayout
      lessonId="linux-01"
      courseId="linux"
      title="Linux File System Hierarchy"
      courseTitle="Linux Fundamentals"
      courseHref="/linux"
      xp={50}
      readTime="~20 min"
      icon="📁"
      breadcrumbs={[
        { label: 'Home', href: '/' },
        { label: 'Linux Fundamentals', href: '/linux' },
        { label: 'File System Hierarchy' },
      ]}
      prev={null}
      next={{ title: 'Shell Basics & Command Line', href: '/linux/shell' }}
      objectives={[
        'Understand the FHS (Filesystem Hierarchy Standard)',
        'Know the purpose of every top-level directory',
        'Navigate and inspect the filesystem with confidence',
        'Understand hard links vs symbolic links',
        'Use df and du to analyse disk usage',
      ]}
    >
      {/* ── OVERVIEW ── */}
      <section>
        <h2>Overview</h2>
        <p>
          Linux uses a single unified directory tree rooted at <code className="font-mono text-accent-cyan text-sm">/</code> (the root),
          regardless of how many physical disks or partitions exist. This is defined by the
          <strong> Filesystem Hierarchy Standard (FHS)</strong> — the map every sysadmin must know cold.
        </p>
        <p className="mt-4">
          Unlike Windows where each drive gets a letter (C:\, D:\), Linux mounts everything
          under one tree. A second disk might be mounted at <code className="font-mono text-accent-cyan text-sm">/data</code> or
          <code className="font-mono text-accent-cyan text-sm"> /mnt/backup</code> — still part of the same tree.
        </p>
      </section>

      {/* ── FHS MAP ── */}
      <section>
        <h2>The Directory Map</h2>
        <div className="info-card overflow-hidden">
          <div className="font-mono text-xs leading-7 overflow-x-auto">
            <div className="min-w-[500px]">
              {[
                { dir: '/',       desc: 'Root of the entire filesystem', color: 'text-white' },
                { dir: '/bin',    desc: 'Essential user binaries (ls, cp, mv, bash) — available in single-user mode', color: 'text-accent-green' },
                { dir: '/sbin',   desc: 'System binaries for root (fsck, iptables, reboot)', color: 'text-accent-green' },
                { dir: '/etc',    desc: 'System-wide configuration files — the most important directory', color: 'text-accent-cyan' },
                { dir: '/home',   desc: 'User home directories (/home/alice, /home/bob)', color: 'text-brand-300' },
                { dir: '/root',   desc: 'Root user\'s home directory — NOT inside /home', color: 'text-accent-amber' },
                { dir: '/var',    desc: 'Variable data: logs (/var/log), mail, caches, databases', color: 'text-accent-amber' },
                { dir: '/tmp',    desc: 'Temporary files — cleared on reboot. World-writable.', color: 'text-slate-400' },
                { dir: '/usr',    desc: 'User programs and data — /usr/bin, /usr/lib, /usr/share', color: 'text-accent-green' },
                { dir: '/opt',    desc: 'Optional/third-party software (e.g., /opt/google/chrome)', color: 'text-slate-400' },
                { dir: '/lib',    desc: 'Shared libraries for binaries in /bin and /sbin', color: 'text-slate-400' },
                { dir: '/proc',   desc: 'Virtual FS — kernel and process info. Nothing stored on disk.', color: 'text-accent-purple' },
                { dir: '/sys',    desc: 'Virtual FS — kernel device and driver info', color: 'text-accent-purple' },
                { dir: '/dev',    desc: 'Device files (block devices, character devices, /dev/null, /dev/sda)', color: 'text-accent-red' },
                { dir: '/mnt',    desc: 'Temporary manual mount points (external drives, NFS)', color: 'text-slate-400' },
                { dir: '/media',  desc: 'Removable media auto-mount points (USB, CD)', color: 'text-slate-400' },
                { dir: '/boot',   desc: 'Bootloader files, kernel image, initramfs', color: 'text-accent-amber' },
                { dir: '/run',    desc: 'Runtime data since last boot (PIDs, sockets). Clears on reboot.', color: 'text-slate-500' },
              ].map(d => (
                <div key={d.dir} className="flex gap-3 border-b border-surface-700/50 last:border-0 py-1">
                  <span className={`w-20 flex-shrink-0 font-bold ${d.color}`}>{d.dir}</span>
                  <span className="text-slate-400">{d.desc}</span>
                </div>
              ))}
            </div>
          </div>
        </div>

        <Callout type="info" icon="💡" title="The three most important directories">
          As a sysadmin you will spend 80% of your time in <strong>/etc</strong> (configs),
          <strong> /var/log</strong> (logs), and <strong>/home</strong> (user data).
          Know these inside-out first.
        </Callout>
      </section>

      {/* ── /etc deep dive ── */}
      <section>
        <h2>/etc — The Configuration Directory</h2>
        <p>Every service you install puts its main config in <code className="font-mono text-accent-cyan text-sm">/etc</code>. Key files every sysadmin must know:</p>
        <div className="mt-4 space-y-2">
          {[
            { file: '/etc/passwd',        desc: 'User account database — username, UID, GID, home dir, shell. Readable by all users.' },
            { file: '/etc/shadow',        desc: 'Encrypted passwords and password policy. Root-only readable.' },
            { file: '/etc/group',         desc: 'Group definitions — group name, GID, members.' },
            { file: '/etc/fstab',         desc: 'Filesystem mount table — defines what gets mounted at boot.' },
            { file: '/etc/hosts',         desc: 'Static hostname-to-IP mappings. Checked before DNS.' },
            { file: '/etc/resolv.conf',   desc: 'DNS resolver configuration — nameservers and search domains.' },
            { file: '/etc/ssh/sshd_config', desc: 'SSH daemon configuration — port, auth methods, allowed users.' },
            { file: '/etc/sudoers',       desc: 'sudo permissions. Always edit with visudo to prevent syntax errors.' },
            { file: '/etc/crontab',       desc: 'System-wide cron schedule.' },
            { file: '/etc/os-release',    desc: 'OS identification — distro name, version, ID.' },
          ].map(f => (
            <div key={f.file} className="flex gap-3 py-2.5 border-b border-surface-700 last:border-0">
              <code className="text-accent-cyan text-xs font-mono w-52 flex-shrink-0 pt-0.5">{f.file}</code>
              <p className="text-sm text-slate-400">{f.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* ── HARD VS SOFT LINKS ── */}
      <section>
        <h2>Hard Links vs Symbolic Links</h2>
        <div className="grid sm:grid-cols-2 gap-4 mt-4">
          <div className="info-card py-4">
            <p className="text-xs font-semibold text-accent-cyan uppercase tracking-widest mb-3">Hard Link</p>
            <ul className="space-y-1.5 text-xs text-slate-400">
              <li className="flex gap-2"><span className="text-brand-400">▸</span> Points to the same inode (data blocks on disk)</li>
              <li className="flex gap-2"><span className="text-brand-400">▸</span> Deleting the original doesn't break the link</li>
              <li className="flex gap-2"><span className="text-brand-400">▸</span> Cannot cross filesystem boundaries</li>
              <li className="flex gap-2"><span className="text-brand-400">▸</span> Cannot link to directories (usually)</li>
              <li className="flex gap-2"><span className="text-brand-400">▸</span> Same file size shown for both entries</li>
            </ul>
            <CodeBlock code="ln /etc/hosts ~/hosts-link" language="bash" className="mt-3" />
          </div>
          <div className="info-card py-4">
            <p className="text-xs font-semibold text-accent-amber uppercase tracking-widest mb-3">Symbolic (Soft) Link</p>
            <ul className="space-y-1.5 text-xs text-slate-400">
              <li className="flex gap-2"><span className="text-accent-amber">▸</span> Points to a path (not an inode)</li>
              <li className="flex gap-2"><span className="text-accent-amber">▸</span> Breaks if the original is moved or deleted</li>
              <li className="flex gap-2"><span className="text-accent-amber">▸</span> Can cross filesystem boundaries</li>
              <li className="flex gap-2"><span className="text-accent-amber">▸</span> Can link to directories</li>
              <li className="flex gap-2"><span className="text-accent-amber">▸</span> Shows as <code className="text-accent-cyan">l</code> in ls -la, with → target</li>
            </ul>
            <CodeBlock code="ln -s /etc/nginx/nginx.conf ~/nginx.conf" language="bash" className="mt-3" />
          </div>
        </div>
      </section>

      {/* ── LAB ── */}
      <section>
        <h2>VMware Lab Exercise</h2>
        <div className="lab-block">
          <div className="lab-header">
            <span className="lab-badge">LAB 1</span>
            <span className="text-sm font-semibold text-white">Explore the Linux Filesystem</span>
            <span className="ml-auto text-xs text-slate-500 font-mono">~15 min</span>
          </div>
          <div className="lab-body space-y-8">
            <LabStep number={1} description="SSH into your Ubuntu Server VM and explore the top-level directory structure."
              command={CODE_LINUXFILESYSTEM_1}
              output={CODE_LINUXFILESYSTEM_2} />

            <LabStep number={2} description="Inspect disk usage — see which directories are consuming space."
              command={CODE_LINUXFILESYSTEM_3}
              output={CODE_LINUXFILESYSTEM_4} />

            <LabStep number={3} description="Explore the /proc virtual filesystem — read live kernel data."
              command={CODE_LINUXFILESYSTEM_5}
            />

            <LabStep number={4} description="Create a directory structure and practice links."
              command={CODE_LINUXFILESYSTEM_6}
            />

            <Callout type="success" icon="✅" title="Lab Complete">
              You can navigate the Linux filesystem, identify directory purposes,
              analyse disk usage, and create both types of links.
            </Callout>
          </div>
        </div>
      </section>

      {/* ── QUICK REF ── */}
      <section>
        <h2>Quick Reference</h2>
        <CodeBlock title="Filesystem Navigation Commands" language="bash" code={CODE_LINUXFILESYSTEM_7} />
      </section>

      {/* ── QUIZ ── */}
      <section>
        <h2>Lesson Quiz</h2>
        <p className="mb-6 text-slate-400 text-sm">5 questions · Pass at 70% to earn bonus XP.</p>
        <Quiz lessonId="linux-01" title="Linux Filesystem Hierarchy Quiz"
              questions={QUIZ_QUESTIONS} passingScore={70} xpReward={25} />
      </section>
    </LessonLayout>
  )
}
